Baremetal tests: Run tests on qemu too.

diff --git a/test/baremetal/Makefile b/test/baremetal/Makefile
--- a/test/baremetal/Makefile
+++ b/test/baremetal/Makefile
@@ -13,11 +13,13 @@ LD=${SDK}/bin/ld
 AS=${SDK}/bin/llvm-mc
 CLANG=${SDK}/bin/clang
 SAIL_EMULATOR=../../c_emulator/cheri_riscv_sim_RV64
+QEMU_EMULATOR=${HOME}/cheri/build/qemu-build/qemu-system-riscv64cheri
 
 TEST_ASMS:=$(wildcard test_*.s)
 TEST_OBJS:=$(TEST_ASMS:.s=.o)
 TEST_ELFS:=$(TEST_ASMS:.s=.elf)
-TEST_OUTS:=$(TEST_ASMS:.s=.out)
+TEST_SAIL_OUTS:=$(TEST_ASMS:.s=.sail_out)
+TEST_QEMU_OUTS:=$(TEST_ASMS:.s=.qemu_out)
 
 %.o: %.s epilogue.s
 	${AS} -triple=riscv64 -mattr=+xcheri,xcherimemversion -filetype=obj -o $@ $<
@@ -28,18 +30,38 @@ TEST_OUTS:=$(TEST_ASMS:.s=.out)
 ${SAIL_EMULATOR}:
 	$(MAKE) -C ../.. csim
 
-%.out: %.elf ${SAIL_EMULATOR}
+%.sail_out: %.elf ${SAIL_EMULATOR}
 	${SAIL_EMULATOR} $< >$@ 2>&1
 
-.PHONY: run
-run: ${TEST_OUTS}
+%.qemu_out: %.elf ${QEMU_EMULATOR}
+	(${QEMU_EMULATOR} -machine spike -d instr -bios $< >$@ 2>&1 \
+	&& echo SUCCESS >> $@) \
+	|| echo FAILURE >> $@
+
+
+.PHONY: run_sail
+run_sail: ${TEST_SAIL_OUTS}
+	@echo "Sail Results:"
 	@echo -n 'Passes: '
-	@grep -l SUCCESS ${TEST_OUTS} || echo none
+	@grep -l SUCCESS ${TEST_SAIL_OUTS} || echo none
 	@echo -n 'Failures: '
-	@grep -l FAILURE ${TEST_OUTS} || echo none
+	@grep -l FAILURE ${TEST_SAIL_OUTS} || echo none
 	@echo -n 'Missing result: '
-	@grep -L 'SUCCESS\|FAILURE' ${TEST_OUTS} && echo none
+	@grep -L 'SUCCESS\|FAILURE' ${TEST_SAIL_OUTS} && echo none
+
+.PHONY: run_qemu
+run_qemu: ${TEST_QEMU_OUTS}
+	@echo "Qemu Results:"
+	@echo -n 'Passes: '
+	@grep -l SUCCESS ${TEST_QEMU_OUTS} || echo none
+	@echo -n 'Failures: '
+	@grep -l FAILURE ${TEST_QEMU_OUTS} || echo none
+	@echo -n 'Missing result: '
+	@grep -L 'SUCCESS\|FAILURE' ${TEST_QEMU_OUTS} && echo none
+
+.PHONY: run
+run: run_sail run_qemu
 
 .PHONY: clean
 clean:
-	rm -f ${TEST_OBJS} ${TEST_ELFS} ${TEST_OUTS}
+	rm -f ${TEST_OBJS} ${TEST_ELFS} ${TEST_SAIL_OUTS} ${TEST_QEMU_OUTS}
